"""Tests for the pipeline scripts. Run from the repo root: python3 -m unittest discover -s tests -t ."""

import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import build_page  # noqa: E402
import run_prompts  # noqa: E402
import usage_report  # noqa: E402

FIX = ROOT / "templates" / "demo-page" / "fixture"


class BuildPage(unittest.TestCase):
    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp())

    def tearDown(self):
        shutil.rmtree(self.tmp)

    def build(self):
        build_page.main(["--spec", str(FIX / "spec.json"), "--plan", str(FIX / "prompt_plan.json"),
                         "--results", str(FIX / "results.json"), "--out", str(self.tmp)])

    def test_inline_data_matches_data_json(self):
        self.build()
        page = (self.tmp / "index.html").read_text()
        inline = page.split('<script id="demo-data" type="application/json">')[1].split("</script>")[0]
        self.assertEqual(json.loads(inline), json.loads((self.tmp / "data.json").read_text()))

    def test_provenance_labels(self):
        self.build()
        cases = json.loads((self.tmp / "data.json").read_text())["cases"]
        self.assertEqual(cases[0]["provenance"]["label"],
                         "Generated by claude-sonnet-5 using this project's prompt on invented inputs")
        self.assertEqual(cases[1]["provenance"]["label"], "Illustrative, written by the agent")

    def test_no_external_requests(self):
        self.build()
        page = (self.tmp / "index.html").read_text()
        for bad in ('src="http', "src='http", 'href="http', "@import", "url(http"):
            self.assertNotIn(bad, page)
        self.assertIn("default-src 'none'", page)

    def test_rejects_svg_with_script_or_link(self):
        for bad in ('<svg><script>alert(1)</script></svg>', '<svg><a href="https://x.test">x</a></svg>',
                    '<svg><rect onclick="x()"/></svg>'):
            p = self.tmp / "d.svg"
            p.write_text(bad)
            with self.assertRaises(build_page.BuildError):
                build_page.load_svg(p)

    def test_summary_required_when_prompt_private(self):
        spec = {"cases": [{"id": "a", "label": "A", "input": "x", "output_illustrative": "y"}],
                "title": "t", "tagline": "t", "what_it_does": []}
        with self.assertRaises(build_page.BuildError):
            build_page.build_data(spec, {}, {})

    def test_script_tag_in_data_is_escaped(self):
        spec = json.loads((FIX / "spec.json").read_text())
        spec["cases"][1]["output_illustrative"] = "</script><script>alert(1)</script>"
        data, _ = build_page.build_data(spec, {}, {})
        page = build_page.render(data, "<svg></svg>")
        self.assertEqual(page.count("</script>"), 2)  # only the two real closing tags


class RunPrompts(unittest.TestCase):
    def test_runs_then_reuses_cache(self):
        tmp = Path(tempfile.mkdtemp())
        try:
            plan = tmp / "plan.json"
            plan.write_text(json.dumps({"cases": [{"id": "a", "system": "s", "messages": [{"role": "user", "content": "hi"}]}]}))
            calls = []

            def fake(body, key):
                calls.append(body)
                return {"model": "claude-sonnet-5", "stop_reason": "end_turn",
                        "content": [{"type": "text", "text": "hello"}],
                        "usage": {"input_tokens": 1000, "output_tokens": 100}}

            import os
            os.environ["ANTHROPIC_API_KEY"] = "test"
            r1 = run_prompts.main(plan, tmp / "results.json", call_fn=fake)
            r2 = run_prompts.main(plan, tmp / "results.json", call_fn=fake)
            self.assertEqual(len(calls), 1)
            self.assertEqual(r1["cases"]["a"]["output"], "hello")
            self.assertEqual(r2["spent"]["calls"], 1)
            self.assertIsNotNone(r1["cost_usd"])
        finally:
            shutil.rmtree(tmp)

    def test_refusal_has_no_output(self):
        tmp = Path(tempfile.mkdtemp())
        try:
            plan = tmp / "plan.json"
            plan.write_text(json.dumps({"cases": [{"id": "a", "messages": [{"role": "user", "content": "x"}]}]}))
            import os
            os.environ["ANTHROPIC_API_KEY"] = "test"
            r = run_prompts.main(plan, tmp / "r.json", call_fn=lambda b, k: {
                "model": "m", "stop_reason": "refusal", "content": [], "usage": {}})
            self.assertIsNone(r["cases"]["a"]["output"])
        finally:
            shutil.rmtree(tmp)


class UsageReport(unittest.TestCase):
    def test_reads_result_entry(self):
        tmp = Path(tempfile.mkdtemp())
        try:
            f = tmp / "exec.json"
            f.write_text(json.dumps([{"type": "system"}, {"type": "result", "total_cost_usd": 0.42, "num_turns": 7,
                                                          "usage": {"input_tokens": 10, "output_tokens": 20}}]))
            self.assertEqual(usage_report.agent_usage(f)["cost"], 0.42)
            self.assertIsNone(usage_report.agent_usage(tmp / "missing.json"))
        finally:
            shutil.rmtree(tmp)


if __name__ == "__main__":
    unittest.main()
