"""Phase 6: build the demo page from templates/demo-page/page.html.

  python3 scripts/build_page.py --spec work/demo/spec.json --plan work/demo/prompt_plan.json \
      --results work/demo/results.json --out output/

Writes output/index.html (with the data inline) and output/data.json from the same object,
and copies the diagram to output/diagram.svg. The leak scanner checks the two data copies match.

Provenance is decided here, not by the agent:
  - a case with an API result gets "Generated by <model> using this project's prompt on invented inputs",
    where <model> is the model the API reported;
  - a case with only "output_illustrative" gets "Illustrative, written by the agent".
"""

import argparse
import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "templates" / "demo-page" / "page.html"

GENERATED = "Generated by {model} using this project's prompt on invented inputs"
ILLUSTRATIVE = "Illustrative, written by the agent"
UNSAFE_SVG = re.compile(r"<script|<foreignObject|\son[a-z]+\s*=|(?:xlink:)?href\s*=\s*[\"'](?!#)", re.I)


class BuildError(Exception):
    pass


def prompt_text(plan_case):
    parts = []
    if plan_case.get("system"):
        parts.append("SYSTEM\n" + plan_case["system"])
    for m in plan_case.get("messages", []):
        content = m["content"]
        if isinstance(content, list):
            content = "\n".join(b.get("text", "") for b in content if isinstance(b, dict))
        parts.append(m["role"].upper() + "\n" + content)
    return "\n\n".join(parts)


def load_svg(path):
    svg = Path(path).read_text(encoding="utf-8")
    svg = re.sub(r"<\?xml[^>]*\?>", "", svg).strip()
    if not svg.startswith("<svg"):
        raise BuildError(f"{path} is not an SVG file")
    if UNSAFE_SVG.search(svg):
        raise BuildError(f"{path} contains scripts, event handlers or links; diagrams must be plain shapes and text")
    return svg


def build_data(spec, plan, results):
    plan_cases = {c["id"]: c for c in plan.get("cases", [])}
    result_cases = results.get("cases", {})
    cases, skipped = [], []
    for c in spec["cases"]:
        cid = c["id"]
        res = result_cases.get(cid)
        if res and res.get("output"):
            output = res["output"]
            prov = {"kind": "generated", "label": GENERATED.format(model=res["model"])}
        elif c.get("output_illustrative"):
            output = c["output_illustrative"]
            prov = {"kind": "illustrative", "label": ILLUSTRATIVE}
        else:
            skipped.append(cid)
            continue
        show_full = c.get("prompt_shown", "summary") == "full" and cid in plan_cases
        if show_full:
            prompt = prompt_text(plan_cases[cid])
            note = c.get("prompt_note", "This is the exact prompt the project sends, filled in with the invented input.")
        else:
            prompt = c.get("prompt_summary", "")
            if not prompt:
                raise BuildError(f"case {cid}: prompt_shown is not 'full', so prompt_summary is required")
            note = c.get("prompt_note", "The project's prompt is private, so this is a summary of what it asks for.")
        cases.append({"id": cid, "label": c["label"], "input": c["input"], "prompt": prompt,
                      "prompt_note": note, "output": output, "provenance": prov})
    if not cases:
        raise BuildError("no case has an output: run scripts/run_prompts.py or add output_illustrative")
    return {
        "title": spec["title"],
        "tagline": spec["tagline"],
        "what_it_does": spec["what_it_does"],
        "built_with": spec.get("built_with", ""),
        "diagram_caption": spec.get("diagram_caption", ""),
        "cases": cases,
        "not_shown": spec.get("not_shown", []),
    }, skipped


def render(data, svg):
    page = TEMPLATE.read_text(encoding="utf-8")
    inline = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    what = "\n    ".join(f"<p>{html.escape(p)}</p>" for p in data["what_it_does"])
    built = f"Built with: {html.escape(data['built_with'])}" if data["built_with"] else ""
    for key, value in {
        "{{TITLE}}": html.escape(data["title"]),
        "{{TAGLINE}}": html.escape(data["tagline"]),
        "{{WHAT_IT_DOES}}": what,
        "{{BUILT_WITH}}": built,
        "{{DIAGRAM_SVG}}": svg,
        "{{DIAGRAM_CAPTION}}": html.escape(data["diagram_caption"]),
        "{{DATA_JSON}}": inline,
    }.items():
        page = page.replace(key, value)
    return page


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True)
    ap.add_argument("--plan", help="prompt_plan.json (needed to show full prompts)")
    ap.add_argument("--results", help="results.json from run_prompts.py")
    ap.add_argument("--out", required=True)
    args = ap.parse_args(argv)

    spec_path = Path(args.spec)
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    plan = json.loads(Path(args.plan).read_text(encoding="utf-8")) if args.plan and Path(args.plan).exists() else {}
    results = json.loads(Path(args.results).read_text(encoding="utf-8")) if args.results and Path(args.results).exists() else {}
    try:
        svg = load_svg(spec_path.parent / spec.get("diagram", "diagram.svg"))
        data, skipped = build_data(spec, plan, results)
    except KeyError as exc:
        sys.exit(f"build_page: spec.json is missing the field {exc}")
    except BuildError as exc:
        sys.exit(f"build_page: {exc}")

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "index.html").write_text(render(data, svg), encoding="utf-8")
    (out / "data.json").write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (out / "diagram.svg").write_text(svg + "\n", encoding="utf-8")
    kinds = [c["provenance"]["kind"] for c in data["cases"]]
    print(f"Built {out / 'index.html'}: {kinds.count('generated')} generated, {kinds.count('illustrative')} illustrative")
    if skipped:
        print(f"Skipped (no output, e.g. the model declined): {', '.join(skipped)}")


if __name__ == "__main__":
    main()
